#!/usr/bin/ksh


## /orad003/global_inventory/ContentsXML/inventory.xml
#
GI=`awk -F= '/^inventory_loc/ {print $2}' /etc/oraInst.loc`
GI_XML=${GI}/ContentsXML/inventory.xml

SID=${1:-D003}

function get_sids  
{

  awk -F: ' ! /^#/  && ! /^$/  {print tolower($1)}' /export/vtssupp/velos/etc/appsoratab|sort

} ### end of get_sids ###

function print_header
{
  awk ' BEGIN {
    printf "\n%-6s %30s  %30s\n", "SID", "Home Name", "Location";
    printf "------ ------------------------------------- ---------------------------------------\n";
  }'

}   ### end of print_header ###



function check_homes
{
  
  grep $1 $GI_XML | awk ' BEGIN {
    NSID="";
    CNT=0;
  }
  
  /HOME NAME/ { 
    split($2,h,"=");
    split($3,l,"=");
    split(l[2],u,"/");
    OSID=substr(u[2],length(u[2])-3,4);
  
    printf "%-6s %-50s %-50s\n", "", h[2], l[2];
    CNT = CNT + 1;
  }
  END {
    if ( CNT != 9  && CNT > 0 ) {
      print "###\t\t\tThere are some Oracle Homes MISSING (" CNT ")\t\t\t###";
    }
  }'

} ### end of check_homes ###


##   - - - - MAIN - - - - ##
for l_sid in $(get_sids)
do
  print "\nProcessing $l_sid"
  check_homes $l_sid
done
